name: SSH Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy via SSH
      env:
        SSH_PASSWORD: ${{ secrets.PASSWORD }}
        SSH_ADDRESS: ${{ secrets.IP_ADDRESS }}
      run: |
        run: |
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_ADDRESS
        
    - name: Get into frontend app
      run: cd /home/ubuntu && pwd && ls
