name: SSH Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass && sudo apt install openssh-server

    - name: Deploy via SSH
      env:
        SSH_PASSWORD: ${{ secrets.PASSWORD }}
        SSH_ADDRESS: ${{ secrets.IP_ADDRESS }}
      run: |
        run: |
        sshpass -p "$SSH_PASSWORD" ssh -T -o StrictHostKeyChecking=no $SSH_ADDRESS 'cd /home/ubuntu/metalex/metalex-client && git pull && npm install -g yarn && sudo yarn && pm2 restart 8'
        
    - name: Get into frontend app
      run: pwd
